export const styles = {
    // Shared
    btnPrimary: {
        fontFamily: "'Syne', sans-serif",
        fontSize: 15,
        fontWeight: 600,
        background: "#1D9E75",
        color: "#fff",
        border: "none",
        padding: "14px 36px",
        borderRadius: 100,
        cursor: "pointer",
        letterSpacing: "0.02em",
    },

    // Intro / Language screen
    introWrap: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        height: "100%",
        padding: "2rem",
        gap: "1.75rem",
        textAlign: "center",
        fontFamily: "'DM Sans', sans-serif",
        background: "#FAFAFA",
    },
    badge: {
        fontSize: 11,
        letterSpacing: "0.12em",
        textTransform: "uppercase",
        color: "#888",
        border: "0.5px solid #DDD",
        padding: "5px 14px",
        borderRadius: 20,
    },
    introTitle: {
        fontFamily: "'Syne', sans-serif",
        fontSize: 48,
        fontWeight: 800,
        lineHeight: 1.2,
        letterSpacing: "-0.01em",
        color: "#111",
        maxWidth: 640,
        margin: "0 auto",
    },
    introSub: {
        fontSize: 15,
        color: "#666",
        maxWidth: 360,
        lineHeight: 1.7,
    },
    hbscNote: {
        fontSize: 12,
        color: "#999",
        border: "0.5px solid #EEE",
        borderRadius: 10,
        padding: "8px 16px",
        maxWidth: 340,
        lineHeight: 1.6,
    },

    // Game
    gameWrap: {
        display: "flex",
        flexDirection: "column",
        minHeight: "100%",
        fontFamily: "'DM Sans', sans-serif",
        background: "#FAFAFA",
    },
    gameHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "1rem 1.5rem",
        borderBottom: "0.5px solid #EEE",
    },
    progressTrack: { display: "flex", gap: 5, alignItems: "center" },
    dot: {
        width: 8, height: 8,
        borderRadius: 50,
        background: "#DDD",
        transition: "all 0.3s",
    },
    dotDone: { background: "#1D9E75" },
    dotCurrent: { background: "#1D9E75", width: 22, borderRadius: 4 },
    stepLabel: { fontSize: 12, color: "#888" },
    statsBar: {
        display: "grid",
        gridTemplateColumns: "repeat(4, 1fr)",
        borderBottom: "0.5px solid #EEE",
    },
    statCell: {
        padding: "10px 12px",
        borderRight: "0.5px solid #EEE",
        display: "flex",
        flexDirection: "column",
        gap: 5,
    },
    statLabel: {
        fontSize: 10,
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        color: "#888",
        display: "flex",
        alignItems: "center",
        gap: 4,
    },
    statBarBg: {
        height: 4,
        background: "#EEE",
        borderRadius: 2,
        overflow: "hidden",
    },
    statBarFill: { height: "100%", borderRadius: 2 },
    statNum: { fontSize: 11, fontWeight: 500, color: "#333" },

    scenarioArea: {
        padding: "1.75rem 1.5rem 2rem",
        display: "flex",
        flexDirection: "column",
        gap: "1.25rem",
    },
    sceneContext: { display: "flex", alignItems: "center", gap: 10 },
    sceneEmoji: { fontSize: 32, lineHeight: 1 },
    sceneTag: {
        fontSize: 10,
        textTransform: "uppercase",
        letterSpacing: "0.1em",
        color: "#1D9E75",
        fontWeight: 500,
    },
    sceneTitle: {
        fontFamily: "'Syne', sans-serif",
        fontSize: 20,
        fontWeight: 700,
        color: "#111",
    },
    sceneStory: {
        fontSize: 15,
        lineHeight: 1.75,
        color: "#333",
        borderLeft: "2px solid #1D9E75",
        paddingLeft: 14,
        fontStyle: "italic",
    },
    choicesLabel: {
        fontSize: 11,
        textTransform: "uppercase",
        letterSpacing: "0.1em",
        color: "#888",
    },
    choices: { display: "flex", flexDirection: "column", gap: 8 },
    choiceBtn: {
        display: "flex",
        alignItems: "flex-start",
        gap: 12,
        padding: "12px 16px",
        border: "0.5px solid #DDD",
        borderRadius: 12,
        background: "#FFF",
        cursor: "pointer",
        textAlign: "left",
        fontFamily: "'DM Sans', sans-serif",
        width: "100%",
        transition: "all 0.18s",
    },
    choiceLetter: {
        fontFamily: "'Syne', sans-serif",
        fontSize: 12,
        fontWeight: 700,
        width: 22, height: 22,
        borderRadius: 50,
        border: "1px solid #DDD",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        color: "#888",
        transition: "all 0.18s",
    },
    choiceText: { fontSize: 14, lineHeight: 1.5, color: "#222" },

    // Feedback
    feedbackWrap: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        height: "100%",
        padding: "2rem 1.5rem",
        gap: "1.25rem",
        textAlign: "center",
        fontFamily: "'DM Sans', sans-serif",
        background: "#FAFAFA",
    },
    feedbackEmoji: { fontSize: 48 },
    feedbackTitle: {
        fontFamily: "'Syne', sans-serif",
        fontSize: 22,
        fontWeight: 700,
        color: "#111",
    },
    feedbackText: {
        fontSize: 15,
        lineHeight: 1.75,
        color: "#555",
        maxWidth: 420,
    },
    deltasRow: { display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "center" },
    deltaPill: {
        fontSize: 12,
        padding: "4px 12px",
        borderRadius: 20,
        fontWeight: 500,
    },
    deltaPos: { background: "#E1F5EE", color: "#0F6E56" },
    deltaNeg: { background: "#FAECE7", color: "#993C1D" },
    deltaNeu: { background: "#F5F5F5", color: "#888" },
    hbscFact: {
        background: "#F7F7F7",
        border: "0.5px solid #EEE",
        borderRadius: 12,
        padding: "14px 18px",
        maxWidth: 440,
        textAlign: "left",
        display: "flex",
        gap: 12,
        alignItems: "flex-start",
    },
    factLabel: {
        fontSize: 10,
        textTransform: "uppercase",
        letterSpacing: "0.1em",
        color: "#1D9E75",
        fontWeight: 500,
        marginBottom: 3,
    },
    factText: { fontSize: 13, lineHeight: 1.65, color: "#666" },

    // End
    endWrap: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        padding: "2.5rem 1.5rem 3rem",
        gap: "1.5rem",
        fontFamily: "'DM Sans', sans-serif",
        background: "#FAFAFA",
        minHeight: "100%",
    },
    endHeader: { textAlign: "center" },
    endTitle: {
        fontFamily: "'Syne', sans-serif",
        fontSize: 30,
        fontWeight: 800,
        color: "#111",
    },
    endSub: { fontSize: 14, color: "#888", marginTop: 4 },
    finalStats: {
        display: "grid",
        gridTemplateColumns: "repeat(4, 1fr)",
        gap: 8,
        width: "100%",
        maxWidth: 520,
    },
    finalStatCard: {
        background: "#F0F0F0",
        borderRadius: 12,
        padding: 14,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 4,
    },
    finalStatName: {
        fontSize: 10,
        textTransform: "uppercase",
        letterSpacing: "0.08em",
        color: "#888",
    },
    finalStatVal: {
        fontFamily: "'Syne', sans-serif",
        fontSize: 22,
        fontWeight: 700,
        color: "#111",
    },
    finalStatBarBg: {
        width: "100%", height: 3,
        background: "#DDD",
        borderRadius: 2,
        overflow: "hidden",
        marginTop: 2,
    },
    finalStatBarFill: { height: "100%", borderRadius: 2 },
    aiReport: {
        width: "100%",
        maxWidth: 520,
        border: "0.5px solid #5DCAA5",
        borderRadius: 14,
        padding: "1.25rem 1.5rem",
        background: "#E8F8F2",
        display: "flex",
        flexDirection: "column",
        gap: 10,
    },
    aiReportLabel: {
        fontSize: 11,
        textTransform: "uppercase",
        letterSpacing: "0.1em",
        color: "#0F6E56",
        fontWeight: 600,
    },
    aiLoading: { fontSize: 14, color: "#0F6E56", fontStyle: "italic" },
    dots: { letterSpacing: 2 },
    aiReportText: {
        fontSize: 14,
        lineHeight: 1.8,
        color: "#085041",
        margin: 0,
    },
    restartBtn: {
        fontFamily: "'DM Sans', sans-serif",
        fontSize: 13,
        color: "#888",
        background: "none",
        border: "0.5px solid #DDD",
        padding: "9px 22px",
        borderRadius: 100,
        cursor: "pointer",
    },
};
